name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: release
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libfreetype6-dev libfontconfig1-dev musl-tools build-essential cmake fontconfig
          sudo apt-get install -y musl-dev

      # - name: Install cross
      #   run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          RUST_FONTCONFIG_DLOPEN: on
          PKG_CONFIG_ALLOW_CROSS: 1
          PKG_CONFIG_ALL_STATIC: 1
          CC_x86_64_unknown_linux_musl: musl-gcc
          RUSTFLAGS: "-C target-feature=+crt-static"
        run: cargo build --release --target x86_64-unknown-linux-musl

      - name: Rename binary
        run: mv ./target/x86_64-unknown-linux-musl/release/kebab-bot ./kebab-bot-new

      - name: Send to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: ./kebab-bot-new
          target: ~/kebab-bot-rs
          overwrite: true
