name: Deploy
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install cross
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: x86_64-unknown-linux-musl

      - name: Build
        run: cargo build --release

      - name: Rename binary
        run: mv ./target/x86_64-unknown-linux-musl/release/kebab-bot ./kebab-bot-new

      - name: Send to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: ./kebab-bot-new
          target: ~/kebab-bot-rs
          overwrite: true
