name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: release
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libfreetype6-dev libfontconfig1-dev build-essential cmake fontconfig
          sudo apt-get install -y fonts-noto-cjk fonts-liberation

      - name: Build
        run: cargo build --release

      - name: Rename binary
        run: mv ./target/release/kebab-bot ./kebab-bot-new

      - name: Send to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: ./kebab-bot-new
          target: ~/kebab-bot-rs
          overwrite: true
